remote_theme: pages-themes/minima@v0.3.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Pedang Langit Dan Golok Pembunuh Naga
description: > 
  Terjemahan dari novel Jin Yong, Yitian Tulong Ji, 
  yang menceritakan petualangan Zhang Wuji, Zhao Min dan Zhou Zhiruo.
